In [33]:
import pandas as pd
import numpy as np
df = pd.read_excel("Problem_C_Data_Wordle.xlsx", names=["Drop", "Date", "ContestNumber", "Word", "ReportedResults", "NumberInHardMode", "1Try", "2Tries", "3Tries", "4Tries", "5Tries", "6Tries", "7Tries"])
# df.drop(columns="Drop")
# df.tail(-1)
df = df.iloc[1:]
df = df.drop(columns="Drop")

df['Word']
for i in df['Word']:
    if (len(i)!=5):
        print(i, len(i))

rprobe 6
clen 4
tash 4
favor  6

In [26]:
for i in ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]:
    curVar = 'contains' + i
    df[curVar] = [True if x.__contains__(i) else False for x in df['Word']]

df

,Date,ContestNumber,Word,ReportedResults,NumberInHardMode,1Try,2Tries,3Tries,4Tries,5Tries,...,containsq,containsr,containss,containst,containsu,containsv,containsw,containsx,containsy,containsz
1,2022-12-31 00:00:00,560,manly,20380,1899,0,2,17,37,29,...,False,False,False,False,False,False,False,False,True,False
2,2022-12-30 00:00:00,559,molar,21204,1973,0,4,21,38,26,...,False,True,False,False,False,False,False,False,False,False
3,2022-12-29 00:00:00,558,havoc,20001,1919,0,2,16,38,30,...,False,False,False,False,False,True,False,False,False,False
4,2022-12-28 00:00:00,557,impel,20160,1937,0,3,21,40,25,...,False,False,False,False,False,False,False,False,False,False
5,2022-12-27 00:00:00,556,condo,20879,2012,0,2,17,35,29,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355,2022-01-11 00:00:00,206,drink,153880,3017,1,9,35,34,16,...,False,True,False,False,False,False,False,False,False,False
356,2022-01-10 00:00:00,205,query,107134,2242,1,4,16,30,30,...,True,True,False,False,True,False,False,False,True,False
357,2022-01-09 00:00:00,204,gorge,91477,1913,1,3,13,27,30,...,False,True,False,False,False,False,False,False,False,False
358,2022-01-08 00:00:00,203,crank,101503,1763,1,5,23,31,24,...,False,True,False,False,False,False,False,False,False,False
359,2022-01-07 00:00:00,202,slump,80630,1362,1,3,23,39,24,...,False,False,True,False,True,False,False,False,False,False

In [27]:
df.to_csv("ContainsDataset.csv")